FORMAT: 1A

# DataOpera - Interoperabilidade de Dados Clínicos

Este documento tem o objetivo de especificar técnicamente como os parceiros devem enviar as mensagens com dados clínicos dos paciente para integração com a plataforma DataOpera.



