FORMAT: 1A
HOST:  https://

# DataOpera - Interoperabilidade de Dados Clínicos

Este documento tem o objetivo de especificar técnicamente como os parceiros devem enviar as mensagens com dados clínicos dos paciente para integração com a plataforma DataOpera.




# DataOpera - Interoperabilidade de Dados Clínicos

Este documento tem o objetivo de especificar técnicamente como os parceiros devem enviar as mensagens com dados clínicos dos paciente para integração com a plataforma DataOpera.


# Group Serviços da API

## Autenticação OAuth [/tune.dataopera.com.br/api/oauth]

### Autenticação [POST] 

Serviço para obtenção do token de acesso que autoriza o uso dos demais serviços.

Utilizamos o **[OAuth](https://oauth.net)** ou **Basic Authentication** como métodos de autorização à API. 
A autenticação se dá através de credendiais de acesso (id e senha) fornecidas pela DataOpera (enviamos por e-mail)
que, no caso de OAuth se faz necessário acessar serviço abaixo para gerar um token de acesso com autorização para o uso do serviços dataopera.

Com o token de acesso gerado, basta colocar no cabeçalho do HTTP usando Authorization na chamada do endpoint pretendido.

```
Authorization: Bearer GENERATED_TOKEN
```    

##### Tabela de Status

| Code   | Description
|:-------|---------------
|01      | Paciente encontrado e com informações clínicas.
|02      | Paciente encontrado sem informações clínicas.
|03      | Paciente não cadastrado e não possui consentimento.
|04      | Mais de um registro encontrado com os dados enviados. 
|05      | Credenciais inválidas.

+ Request Quando irá acessar apis sem necessecidade de informa paciente. (application/json)  

        {
            "grant_type": "client_credentials",
            "client_id": "1",
            "client_secret": "123456"
        }
        
+ Request Quando irá acessar DATAMEA informando o paciente por meio do publicToken/MPI (application/json)

        {
            "grant_type": "client_credentials",
            "client_id": "1",
            "client_secret": "123456",
            "patient": {
                "publicToken": "00000000-0000-0000-0000-000000000000"
            }
        }

+ Request Quando irá acessar DATAMEA informando o paciente por meio dos dados de identificação (application/json)

        {
            "grant_type": "client_credentials",
            "client_id": "1",
            "client_secret": "123456",
            "patient": {
                "nomeCompleto" : "PESSOA EXEMPLO",
                "cpf" : "000.000.000-00",
                "rg" : "0000000000",
                "cns" : "0000000000",
                "nomeMae" : "NOME MAE PESSOA EXEMPLO",
                "dataNascimento" : "0000-00-00",
                "nascimentoPais":"Brasil",                
                "sexo" : "M",
                "residenciaCidade" : "SÃO PAULO",
                "residenciaUf" : "SP",
                "nascimentoPais": "Brasil",
                "contatoCelular": "11900000000",
                "contatoEmail" : "nome@dominio.com"
            }
        }

+ Response 200 (application/json)
    + Body

            {
                "access_token": "0000000000000000000000000000000000000",
                "expires_in": 7200,
                "token_type": "Bearer",
                "scope": ""
            }


## Envio de dados clinicos [/tune.dataopera.com.br/api/message]

### Envio de dados clinicos [POST]

Serviço para o envio dos dados de um atendimento clínico de um paciente.
O padrão a ser utilizado no document odeverá ser definido em temp ode projeto, a preferência é por utilizar o padrão HL7 FHIR (https://www.dataopera.com.br/fhir-guide/artifacts.html), mas é possivel utilizar padrão customizado de acordo  com as necessidades do cliente/parceiro.

+ request  Dados em padrão HL7 FHIR (https://www.dataopera.com.br/fhir-guide/artifacts.html). (application/fhir+json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
    
            {
                "resourceType" : "Bundle",
                "type" : "collection",
                "entry" : [ 
                    {
                        "resource" : {
                            "resourceType" : "Patient",
                            "id" : "1234",
                            "identifier" : [ 
                                {
                                    "use" : "official",
                                    "type" : {
                                        "text" : "CPF"
                                    },
                                    "value" : "00000000000"
                                }
                            ],
                            "name" : [ 
                                {
                                    "use" : "official",
                                    "family" : "EXEMPLO",
                                    "given" : [ 
                                        "PACIENTE"
                                    ]
                                }
                            ],
                            "gender" : "male",
                            "birthDate" : "1981-01-09"
                        }
                    }, 
                    {
                        "resource" : {
                            "resourceType" : "AllergyIntolerance",
                            "id" : "2348|46",
                            "identifier" : [ 
                                {
                                    "value" : "2348|46"
                                }
                            ],
                            "patient" : {
                                "reference" : "Patient/1234"
                            },
                            "reaction" : [ 
                                {
                                    "substance" : {
                                        "coding" : [ 
                                            {
                                                "code" : "46",
                                                "display" : "Castanhas"
                                            }
                                        ]
                                    },
                                    "manifestation" : [ 
                                        {
                                            "coding" : [ 
                                                {
                                                    "code" : "2348|46",
                                                    "display" : "Descriçao da reação"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                ]
            }

+ request Dados em padrão JSON customizado. (application/json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
    
            {
                "message_datetime": "20180501155836",
                "message_id": "1234567890",
                "event":{
                    "recorded_datetime": "20180501155836"
                },
                "sistemaOrigem": "DataMea",
                "paciente":{
                    "id": "123456",
                    "nomeCompleto": "Maria da Silva",
                    "dataNascimento": "19620506",
                    "sexo": "F",
                    "nomeSocial": "Maria",
                    "estadoCivil": "S",
                    "rg": "222222222",
                    "cpf": "11111111111",
                    "cns": "1111111111111",
                    "passaporte": "XXXXXXXXXXX",
                    "nacionalidade": "brasileiro",
                    "paisNascimento": "Brasil",
                    "municipioNascimento": "São Paulo",
                    "endereco":{
                       "logradouro": "Avenida Paulista",
                       "numero": "1472",
                       "bairro": "Jardim Paulista",
                       "cidade": "São Paulo",
                       "uf": "SP",
                       "cep": "75000001",
                       "paisResidencia": "Brasil"
                    },
                    "contatos":{
                        "telefone": "2345678",
                        "email": "mariadasilva@dataopera.com",
                        "celular": "11988888888"
                    }
                },
                "profissional":{
                    "nomeCompleto": "Jose da Silva",
                    "registroProfissional": "11111",
                    "conselho": "CRM",
                    "ufconselho": "SP",
                    "cbo": "225136",
                    "cnsprofissional": "123132132"
                },
                "estabelecimentoSaude": { 
                    "nomeFantasia": "Clinica do Jose",
                    "cnes": "123456789"
                },
                "atendimentoClinico": {
                    "id": "12345678",
                    "dataHoraAdmissao": "20160923155836",
                    "dataHoraDesfecho": "20160923155836",
                    "observacao": "O paciente se queixou de dores de cabeça e dores no corpo.",
                    "diagnosticos":[{
                        "terminologia": "CID10",
                        "codigo": "A90",
                        "descricao": "Dengue [dengue clássico]"
                    }],
                    "procedimentosRealizados":[{
                        "terminologia": "TUSS",
                        "codigo": "10101012",
                        "descricao": "Consultas",
                        "quantidade": 1
                    }],
                    "prescricao":[{
                        "descricao": "CETOPROFENO 100 MG",
                        "posologia": "Tomar 2cp por dia"
                    }],
                    "financiamento": { 
                        "descricao": "Particular",
                        "plano": "",
                        "carteirinha": ""
                    }
                }
            }
        


        
+ Response 200 (application/json)

            {
                "status": "ok",
                "message": "Mensagem processada com sucesso!"
            }
            
## Envio de dados clinicos informando origem [/tune.dataopera.com.br/api/message/{Origem}]

### Envio de dados clinicos [POST]

Serviço para o envio dos dados de um atendimento clínico de um paciente.
O padrão a ser utilizado no document odeverá ser definido em temp ode projeto, a preferência é por utilizar o padrão HL7 FHIR, mas é possivel utilizar padrão customizado de acordo  com as necessidades do cliente/parceiro.

Este endpoint permite informar o sistema origem da infomração, caso o usuario utilizado para gerar o token de autenticação tenha permissão para isso.


+ Parameters
    + Origem (required, string) ...  código do sistema origem das informações.

+ request Dados em padrão JSON customizado. (application/json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
    
            {
                "message_datetime": "20180501155836",
                "message_id": "1234567890",
                "event":{
                    "recorded_datetime": "20180501155836"
                },
                "sistemaOrigem": "DataMea",
                "paciente":{
                    "id": "123456",
                    "nomeCompleto": "Maria da Silva",
                    "dataNascimento": "19620506",
                    "sexo": "F",
                    "nomeSocial": "Maria",
                    "estadoCivil": "S",
                    "rg": "222222222",
                    "cpf": "11111111111",
                    "cns": "1111111111111",
                    "passaporte": "XXXXXXXXXXX",
                    "nacionalidade": "brasileiro",
                    "paisNascimento": "Brasil",
                    "municipioNascimento": "São Paulo",
                    "endereco":{
                       "logradouro": "Avenida Paulista",
                       "numero": "1472",
                       "bairro": "Jardim Paulista",
                       "cidade": "São Paulo",
                       "uf": "SP",
                       "cep": "75000001",
                       "paisResidencia": "Brasil"
                    },
                    "contatos":{
                        "telefone": "2345678",
                        "email": "mariadasilva@dataopera.com",
                        "celular": "11988888888"
                    }
                },
                "profissional":{
                    "nomeCompleto": "Jose da Silva",
                    "registroProfissional": "11111",
                    "conselho": "CRM",
                    "ufconselho": "SP",
                    "cbo": "225136",
                    "cnsprofissional": "123132132"
                },
                "estabelecimentoSaude": { 
                    "nomeFantasia": "Clinica do Jose",
                    "cnes": "123456789"
                },
                "atendimentoClinico": {
                    "id": "12345678",
                    "dataHoraAdmissao": "20160923155836",
                    "dataHoraDesfecho": "20160923155836",
                    "observacao": "O paciente se queixou de dores de cabeça e dores no corpo.",
                    "diagnosticos":[{
                        "terminologia": "CID10",
                        "codigo": "A90",
                        "descricao": "Dengue [dengue clássico]"
                    }],
                    "procedimentosRealizados":[{
                        "terminologia": "TUSS",
                        "codigo": "10101012",
                        "descricao": "Consultas",
                        "quantidade": 1
                    }],
                    "prescricao":[{
                        "descricao": "CETOPROFENO 100 MG",
                        "posologia": "Tomar 2cp por dia"
                    }],
                    "financiamento": { 
                        "descricao": "Particular",
                        "plano": "",
                        "carteirinha": ""
                    }
                }
            }
        

+ request  Dados em padrão HL7 FHIR. (application/fhir+json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
    
            {
                "resourceType" : "Bundle",
                "type" : "collection",
                "entry" : [ 
                    {
                        "resource" : {
                            "resourceType" : "Patient",
                            "id" : "1234",
                            "identifier" : [ 
                                {
                                    "use" : "official",
                                    "type" : {
                                        "text" : "CPF"
                                    },
                                    "value" : "00000000000"
                                }
                            ],
                            "name" : [ 
                                {
                                    "use" : "official",
                                    "family" : "EXEMPLO",
                                    "given" : [ 
                                        "PACIENTE"
                                    ]
                                }
                            ],
                            "gender" : "male",
                            "birthDate" : "1981-01-09"
                        }
                    }, 
                    {
                        "resource" : {
                            "resourceType" : "AllergyIntolerance",
                            "id" : "2348|46",
                            "identifier" : [ 
                                {
                                    "value" : "2348|46"
                                }
                            ],
                            "patient" : {
                                "reference" : "Patient/1234"
                            },
                            "reaction" : [ 
                                {
                                    "substance" : {
                                        "coding" : [ 
                                            {
                                                "code" : "46",
                                                "display" : "Castanhas"
                                            }
                                        ]
                                    },
                                    "manifestation" : [ 
                                        {
                                            "coding" : [ 
                                                {
                                                    "code" : "2348|46",
                                                    "display" : "Descriçao da reação"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                ]
            }
        
+ Response 200 (application/json)

            {
                "status": "ok",
                "message": "Mensagem processada com sucesso!"
            }
            
            

## Consentimento do Paciente [/tune.dataopera.com.br/api/agreement/consent]

### Verificação do Status do Consentimento de Coleta e Compartilhamento de Dados Clínicos do paciente [GET]

Serviço que consulta o status do consentimento de coleta de dados clínicos do paciente informado por meio do Token Público.


+ Parameters
    + publicToken: Token público do paciente. (string, required)

+ request            
    + Header    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    

+ Response 200 (application/json)
    + Body

            {
                "publicToken": "98322343-1faf-41f5-8c76-9d4584c4b405",
                "nome": "Luiz Fernando Piazza Timo Iaria",
                "authToCollect": 
                    {
                       "link": "http://attr.vaultid.cloud//d9/84/d984dbbc3471429caad9a2d41e0485c6/04030005109_1.crt",
                        "createdAt": "2018-11-28 16:26:43"
                    }
                "status:
                    {
                      "status": true,
                      "detail": {
                        "signature": {
                          "status": true,
                          "code": 1185,
                          "message": "All digital signatures of the document are intact"
                        },
                        "date": {
                          "status": true,
                          "code": 1187,
                          "message": "Date of certificate is valid"
                        },
                        "crl": {
                          "status": true,
                          "code": 1191,
                          "message": "CRL is valid"
                        },
                        "trust": {
                          "status": true,
                          "code": 1189,
                          "chain": "Chain of certificate is trusted"
                    }
            }
+ Response 401 (application/json)
    + Body

            "Operador não autenticado"
            
+ Response 406 (application/json)
    + Body

            {
                "status": {
                    "code": "401"
                },
                "details": "Token Inválido."
            }



### Consentimento de Compartilhamento de Dados Clínicos do paciente [POST]

Este endpoint está liberado apenas para parceiros (empresas) que possuem permissão no processo de Consentimento em nome do Paciente, para isso o parceiro se responsábiliza pelo consentimento de compartilhamento dos dados do paciente informado por meio do Token Público.
Para cada consentimento é gerado um certificado digital com os dados da origem do consentimento o qual é válido juridicamente de acordo com as legislações brasileira (LGPD).

Este endpoint está prepara para o modelo de autenticação especificado para o parceiro (OAUTH ou Basic Authentication)

+ Attributes
        + publicToken: Token público do paciente. (string, required)
        + partnerToken: Token de identificação do parceiro [empresa]. (string, required)
        + metadados: Dados de comprovaçã oda captura do consentimento pelo sistema origem. (required)
        
+ request (application/json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
        
            {
                "partner": "CLIENTID-HOMOL",
                "publicToken": "98322343-1faf-41f5-8c76-9d4584c4b405",
                "metadados": {
                    "patient": {
                        "resourceType": "Patient",
                        "id": "2953677",
                        "identifier": [
                            {
                                "type": {
                                    "text": "CPF"
                                },
                                "system": "http://gov.CPF",
                                "value": "12313213213"
                            },
                            {
                                "type": {
                                    "text": "RG"
                                },
                                "system": "http://gov.RG",
                                "value": "32132132"
                            }
                        ],
                        "name": [
                            {
                                "family": "EXEMPLO",
                                "given": [
                                    "PACIENTE"
                                ]
                            }
                        ],
                        "gender": "male",
                        "birthDate": "1981-04-11",
                        "address": [
                            {
                                "use": "home",
                                "line": [
                                    "AV FARIAS LOBATO, 42"
                                ],
                                "city": "São Paulo",
                                "district": "Liberdade"
                            }
                        ]
                    },
                    "environment": "prod",
                    "spvll": "ce4e9e986b0fbc713624d54b83c36283.1f6e0dc3bca3e5db4d9cf827653346a4.2",
                    "organizationId": "312",
                    "identifier": {
                        "key": "carteirinha",
                        "value": "08818181614555"
                    },
                    "consent": {
                        "typeId": "1",
                        "isAccepted": false,
                        "consentAt": "2021-09-12 09:11:22"
                    },
                    "ips": {
                        "forwarded": "5464:132:c7f4:d62e:8444:530:ad99:af40, 192.214.16.12",
                        "remote": "172.29.32.62"
                    },
                    "header": {
                        "agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/86.0.4240.198 Safari\/537.36"
                    }
                }
            }



+ Response 200 (application/json)
    + Body

            { 
                "success": boolean
            }
+ Response 401 (application/json)
    + Body

            "Operador não autenticado"
            
+ Response 406 (application/json)
    + Body

            {
                "status": {
                    "code": "401"
                },
                "details": "Token Inválido."
            }


### Revogação de Consentimento de Compartilhamento de Dados Clínicos do paciente [DELETE]

Este endpoint está liberado apenas para parceiros(empresas) que possuem permissão no processo de Consentimento em nome do Paciente, para isso o parceiro se responsábiliza pelo consentimento de compartilhamento dos dados do paciente informado por meio do Token Público.
Para cada consentimento é gerado um certificado digital com os dados da origem do consentimento o qual é válido juridicamente de acordo com as legislações brasileira (LGPD).

Este endpoint está prepara para o modelo de autenticação especificado para o parceiro (OAUTH ou Basic Authentication)


    
+ request (application/json)
    + Attributes
        + publicToken: Token público do paciente. (string, required)
        + partnerToken: Token de identificação do parceiro [empresa]. (string, required)
        + metadados: Dados de comprovaçã oda captura do consentimento pelo sistema origem. (required)
        
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
        
            {
                "partner": "CLIENTID-HOMOL",
                "publicToken": "98322343-1faf-41f5-8c76-9d4584c4b405",
                "metadados": {
                    "patient": {
                        "resourceType": "Patient",
                        "id": "2953677",
                        "identifier": [
                            {
                                "type": {
                                    "text": "CPF"
                                },
                                "system": "http://gov.CPF",
                                "value": "12313213213"
                            },
                            {
                                "type": {
                                    "text": "RG"
                                },
                                "system": "http://gov.RG",
                                "value": "32132132"
                            }
                        ],
                        "name": [
                            {
                                "family": "EXEMPLO",
                                "given": [
                                    "PACIENTE"
                                ]
                            }
                        ],
                        "gender": "male",
                        "birthDate": "1981-04-11",
                        "address": [
                            {
                                "use": "home",
                                "line": [
                                    "AV FARIAS LOBATO, 42"
                                ],
                                "city": "São Paulo",
                                "district": "Liberdade"
                            }
                        ]
                    },
                    "environment": "prod",
                    "spvll": "ce4e9e986b0fbc713624d54b83c36283.1f6e0dc3bca3e5db4d9cf827653346a4.2",
                    "organizationId": "312",
                    "identifier": {
                        "key": "carteirinha",
                        "value": "08818181614555"
                    },
                    "consent": {
                        "typeId": "1",
                        "isAccepted": false,
                        "consentAt": "2021-09-12 09:11:22"
                    },
                    "ips": {
                        "forwarded": "5464:132:c7f4:d62e:8444:530:ad99:af40, 192.214.16.12",
                        "remote": "172.29.32.62"
                    },
                    "header": {
                        "agent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/86.0.4240.198 Safari\/537.36"
                    }
                }
            }



+ Response 200 (application/json)
    + Body

            { 
                "success": boolean
            }
+ Response 401 (application/json)
    + Body

            "Operador não autenticado"
            
+ Response 406 (application/json)
    + Body

            {
                "status": {
                    "code": "401"
                },
                "details": "Token Inválido."
            }

                        

## Anonimização do Paciente [/tune.dataopera.com.br/api/patient/anonymize]

### Anonimização dos Dados Clínicos do Paciente [POST]

Serviço que anonimiza os dados clínicos do paciente informado por meio do Token Público contido no campo id do resource Patient.

        
+ request (application/json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
            {
                "resourceType": "Patient",
                "id": "a31db1e2-16f9-1df8-a717-7fc9020f19e1",
                "identifier": [
                    {
                        "use": "official",
                        "type": {
                            "text": "CPF"
                        },
                        "value": "0000000000000"
                    }
                ],
                "name": [
                    {
                        "use": "official",
                        "family": "LÍSIAS SALOMÃO",
                        "given": [
                            "PAULO"
                        ]
                    }
                ],
                "gender": "male",
                "birthDate": "1962-02-26"
            }
    

+ Response 200 (application/json)
    + Body

            true

+ Response 401 (application/json)
    + Body

            "Não autorizado"
            
+ Response 406 (application/json)
    + Body

            {
                "status": {
                    "code": "401"
                },
                "details": "Token Inválido."
            }


## Consentimento de Acesso a dados a Organizações Parceiras [/tune.dataopera.com.br/api/consent]

### Consentimento de Acesso a Dados Clínicos do Paciente a Organizações Parceiras [POST]

Serviço que possibilita dar permissão de acesso aos dados clínicos do paciente a organização parceiras. 
Para isso é utilizado o Resource Consent informando o paciente (patient), organização que esta concedento (organization[0].reference) permissão (provision.type = [allo/deny]), organização parceira (provision.actor[0].reference.reference) e identificador do atendimento (provision.data[0].reference.reference).
O identificador da Organização é o login de autenticação no DataOpera.
        
+ request (application/json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
            {
  "resourceType": "Consent",
  "id": "consent-example",  
  "status": "active",
  "scope": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/consentscope",
        "code": "patient-privacy"
      }
    ]
  },
  "patient": {
    "reference": "Patient/a11db0e1-16f9-1d18-a721-1fc9020f69e6",
    "display": "Nome do paciente"
  },
  "dateTime": "2022-03-18",
  "organization": [
    {
      "reference": "Organization/XX-HOMOL"
    }
  ],
  "sourceAttachment": {
    "title": "The terms of the consent in lawyer speak."
  },
  "policyRule": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
        "code": "OPTOUT"
      }
    ]
  },
  "provision": {
    "type": "allow",
    "actor": [
      {
        "role": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code": "CST"
            }
          ]
        },
        "reference": {
          "reference": "Organization/PARTNER-XX-HOMOL"
        }
      }
    ],
    "purpose": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
        "code": "ETREAT"
      }
    ],
    "data": [
            {
                "reference": {
                    "reference": "Encounter/123456"
                }
            }
        ]
  }
}
    

+ Response 200 (application/json)
    + Body
    
            true

+ Response 401 (application/json)
    + Body

            "Não autorizado"
            
+ Response 406 (application/json)
    + Body

            {
                "status": {
                    "code": "401"
                },
                "details": "Token Inválido."
            }
        


## Link de consentimento [/agreementapi.dataopera.com.br]


### Geração de link de consentimento [POST]

Ao enviar os dados do paciente é gerada uma URL para que o paciente possa consentir acesso ao médico/parceiro.
e um public token que servirá para identificação do paciente.

+ request (application/json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/json
    
    + Body
        
            {
                "cliente": "CLIENT_HASH",
                "data": {
                    "idSistemaOrigem": "123456",
                    "nomeCompleto": "Nome Completo",
                    "dataNascimento": "19620506",
                    "nomeMae": "Nome Mãe",
                    "sexo": "F",
                    "rg": "0000000000",
                    "cpf": "00000000000",
                    "cns": "1111111111111",
                    "passaporte": "XXXXXXXXXXX",
                    "nascimentoPais": "Brasil",
                    "residenciaCidade": "São Paulo",
                    "residenciaUf": "SP",
                    "residenciaPais": "Brasil",
                    "contatoEmail": "email@email.com",
                    "contatoCelular": "11988888888"
                }
            }

+ Response 200 (application/json)

    + Body
    
            {
                "url": "https://agreementhomolog.datamea.com.br/#/22c01%7CztzLPHnmieTH3%2BH7Juu65JmyUd1gUp9g%2Fiy5qJWmrXaznE8dKVqvGdALrS7j51gLiT88vTCHBYDsCso8q90%2BvYG66Ytq9olLeJVY1LOrVeRajYM7SQm2v4GlhMjyqLtjZhcDxlCeiNlvozaHQ1nhuikpWqG3bJawgQVWtc5Za93hP5YdhNHc0T8ccGbmx4URvWXSaCzxrELvoWdwMvd4Szur5Ih8tCTfwovK2pnwmPWcWMXo1lRHBhjamHk0kGX6mNPXnQymP%2BDOB3ilNAgSqvg%2BnP6yaTbiwy1hP2pXtzfUZwk4WJbPQv3pyRvPddFsX4IX%2FL6j3sJVL8x8%2FAuIsQ%3D%3D/22dfc93b-0029-4362-83f2-b6907e4d6389",
                "publicToken": "PUBLIC_TOKEN_PATIENT"
            }


## Consulta de dados clinicos [/fhir.dataopera.com.br/v1/?Patient.identifier.value={Patient.identifier.value}&Encounter.identifier.value={Encounter.identifier.value}&_since={_since}&_until={_until}]            

### Consulta de dados clinicos de pacientes [GET]

Serviço que consulta os dados clínicos do paciente por meio do Token Público, identificador de atendimento (sistema origem ou repositório) e período de datas.


+ Parameters
    + Patient.identifier.value (required, string) ...  publicToken/MPI do paciente.
    + Encounter.identifier.value (optional, string) ...  Identificado do atendimento clinico.
    + Encounter.identifier.use (optional, string) ...  Sistema de referencia do identificador de atendimento clinico (official= Sistema origem | usual = Reposistório).
    + _since (optional, string) ...  Filtro de data inicio, caso não informado será buscado desde o primeiro dado clinico. <br><em>Regex:`?([1-9][0-9]{3}|0[0-9]{3})(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01]))?)?`</em>
    + _until (optional, string) ...  Filtro de data fim, caso não informado será buscado até o último dado clinico. <br><em>Regex:`?([1-9][0-9]{3}|0[0-9]{3})(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01]))?)?`</em>

    
+ request (application/fhir+json)
    + Header
    
            Authorization: Bearer GENERATED_TOKEN
            Accept: application/fhir+json;
    

+ Response 200 (application/json)
    + Body

            {
              "resourceType": "Bundle",
              "id": "bundle-history",
              "meta": {
                "lastUpdated": "2019-10-14T08:23:30+11:00"
              },
              "type": "history",
              "link": [
                {
                  "relation": "self",
                  "url": "http://fhir.dataopera.com.br/v1/_history?Patient.identifier.value=91612d7b-cb3a-4612-b0ad-5d9145936870&_since=2019-02-06&_until=2019-02-07"
                }
              ],
              "total": 33,
              "entry": [
                {
                  "resource": {
                    "resourceType": "Patient",
                    "id": "31612d7b-cb3a-4612-b0ad-5d9145936870",
                    "identifier": [
                      {
                        "system": "gov.cns",
                        "value": "881284751090009"
                      }
                    ],
                    "address": [
                      {
                        "city": "4314902",
                        "country": "BRA",
                        "postalCode": "91120250",
                        "state": "43"
                      }
                    ],
                    "deceasedBoolean": false,
                    "extension": [
                      {
                        "url": "mothersName",
                        "valueString": "MARIA HELENA"
                      },
                      {
                        "url": "race",
                        "valueString": "Branca"
                      },
                      {
                        "url": "birthPlace",
                        "valueString": "SÃO PAULO"
                      },
                      {
                        "url": "birthcountry",
                        "valueString": "BRA"
                      }
                    ],
                    "gender": "FEMININO",
                    "language": "PT",
                    "maritalStatus": {
                      "coding": [
                        {
                          "code": "M"
                        }
                      ]
                    },
                    "name": [
                      {
                        "family": [
                          "OLIVEIRA"
                        ],
                        "given": [
                          "FERNANDA"
                        ]
                      }
                    ]
                  }
                },
                {
                  "resource": {
                    "resourceType": "Encounter",
                    "id": "76876876876",
                    "identifier": [
                      {
                        "value": "76876876876"
                      }
                    ],
                    "serviceProvider": {
                      "reference": "Organization/2262568",
                      "display": "HOSPITAL SAO LUCAS"
                    },
                    "origin": {
                      "reference": "Organization/2262568",
                      "display": "HOSPITAL SAO LUCAS"
                    },
                    "participant": [
                      {
                        "individual": {
                          "display": "SIMONE AZEVEDO",
                          "reference": "23456-SP",
                          "identifier": [
                            {
                              "system": "gov.cpf",
                              "value": "99752757022"
                            },
                            {
                              "system": "gov.crm",
                              "value": "23456-SP"
                            }
                          ]
                        },
                        "type": [
                          {
                            "coding": [
                              {
                                "code": "ADM",
                                "system": "http://hl7.org/fhir/participant-type"
                              }
                            ]
                          }
                        ]
                      }
                    ],
                    "period": {
                      "end": "2019-02-06T14:19:33.446Z",
                      "start": "2019-02-06T14:19:33.446Z"
                    },
                    "status": "final",
                    "subject": {
                      "display": "FERNANDA DA SILVEIRA",
                      "reference": "Patient/31612d7b-cb3a-4612-b0ad-5d9145936870"
                    },
                    "extension": [
                      {
                        "url": "assistanceModality",
                        "valueString": "04"
                      }
                    ]
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "ba2df807-b62b-4d63-9373-42edc50d6f8a",
                    "code": {
                      "coding": [
                        {
                          "code": "AMBULATORIO",
                          "display": "AMBULATORIO",
                          "system": "HL7"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/047d8eff-f771-4552-9934-d76cf0a0728c"
                    },
                    "subject": {
                      "display": "FERNANDA DA SILVEIRA",
                      "reference": "Patient/31612d7b-cb3a-4612-b0ad-5d9145936870"
                    },
                    "value": [
                      {
                        "system": "urn:oid:2.16.840.1.113883.2.21.1.122",
                        "code": "90159993",
                        "display": "GLIFAGE 850 MG"
                      }
                    ],
                    "valueString": "GLIFAGE 850 MG-(Glucoformin, Metformina) Tomar 1 cp no café, almoço e janta, aumentando a dose"
                  }
                },
                {
                  "resource": {
                    "resourceType": "DiagnosticReport",
                    "id": "82b8253c-727e-4dbb-859f-2efb3191984a",
                    "identifier": [
                      {
                        "system": "2.16.840.1.113883.6.3",
                        "type": "CID-10"
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/2b88c494-d0d0-48d0-b906-7650b4c1069f"
                    },
                    "status": "final",
                    "category": "principal",
                    "extension": [
                      {
                        "url": "hypothesis",
                        "valueBoolean": "true"
                      }
                    ],
                    "code": {
                      "text": "J45.0",
                      "coding": [
                        {
                          "system": "2.16.840.1.113883.6.3",
                          "type": "CID-10",
                          "code": "I10",
                          "display": "Hipertensão essencial"
                        }
                      ],
                      "status": "S"
                    },
                    "subject": {
                      "display": "FERNANDA DA SILVEIRA",
                      "reference": "Patient/31612d7b-cb3a-4612-b0ad-5d9145936870"
                    },
                    "issued": "2019-07-31T21:45:11-0300"
                  }
                },
                {
                  "resource": {
                    "resourceType": "DocumentReference",
                    "id": "518eb705-2e24-42e8-8baa-92a501a44f5d",
                    "status": "final",
                    "author": [
                      {
                        "reference": "Practictioner/23456-SP"
                      }
                    ],
                    "content": [
                      {
                        "attachment": {
                          "title": "CONSULTA"
                        }
                      }
                    ],
                    "context": {
                      "encounter": {
                        "id": "Encounter/76876876876"
                      }
                    },
                    "subject": {
                      "display": "FERNANDA DA SILVEIRA",
                      "reference": "Patient/31612d7b-cb3a-4612-b0ad-5d9145936870"
                    },
                    "type": {
                      "coding": [
                        {
                          "id": "57833-6",
                          "system": "LOINC"
                        }
                      ],
                      "text": "ANAMNESE"
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "AllergyIntolerance",
                    "id": "46d7ea1b-927a-4199-98a6-de6e011e1e26",
                    "identifier": [
                      {
                        "system": "http://acme.com/ids/patients/risks",
                        "value": "494762223"
                      }
                    ],
                    "type": "allergy",
                    "category": [
                      "food"
                    ],
                    "patient": {
                      "display": "FERNANDA DA SILVEIRA",
                      "reference": "Patient/31612d7b-cb3a-4612-b0ad-5d9145936870"
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "reaction": [
                      {
                        "substance": {
                          "text": "Extrato de caju"
                        },
                        "manifestation": [
                          {
                            "text": "Reação anafilática"
                          }
                        ],
                        "description": "Intolerância a extrato de castanha de caju"
                      }
                    ]
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "9ede742b-3e21-43b5-b7ab-20e9affa77fe",
                    "code": {
                      "coding": [
                        {
                          "code": "AMBULATORIO",
                          "display": "AMBULATORIO",
                          "system": "HL7"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/fc0afb82-fbd9-4e8b-ac7d-e004b611aac2"
                    },
                    "subject": {
                      "display": "MARIA JONES NUNES",
                      "reference": "Patient/a32e05f3-cf45-42c8-bbbc-8566ebedc119"
                    },
                    "extension": [
                      {
                        "url": "continuous",
                        "valueBoolean": "true"
                      }
                    ],
                    "value": [
                      {
                        "system": "urn:oid:2.16.840.1.113883.2.21.1.122",
                        "code": "90159993",
                        "display": "GLIFAGE 850 MG"
                      }
                    ],
                    "valueString": "GLIFAGE 850 MG-(Glucoformin, Metformina) Tomar 1 cp no café, almoço e janta, aumentando a dose"
                  }
                },
                {
                  "resource": {
                    "resourceType": "DocumentReference",
                    "id": "63801f2a-41fd-4b5c-ac90-074211744af6",
                    "status": "final",
                    "author": [
                      {
                        "reference": "Practictioner/23456-SP"
                      }
                    ],
                    "content": [
                      {
                        "attachment": {
                          "title": "CONSULTA"
                        }
                      }
                    ],
                    "context": {
                      "encounter": {
                        "id": "Encounter/76876876876"
                      }
                    },
                    "subject": {
                      "display": "MARIA JONES NUNES",
                      "reference": "Patient/a32e05f3-cf45-42c8-bbbc-8566ebedc119"
                    },
                    "type": {
                      "coding": [
                        {
                          "id": "57833-6",
                          "system": "LOINC"
                        }
                      ],
                      "text": "ANAMNESE"
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "DiagnosticReport",
                    "id": "82c0b31a-95ee-40c9-ae68-3b4a02a1d8a1",
                    "identifier": [
                      {
                        "system": "2.16.840.1.113883.6.3",
                        "type": "CID-10"
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/63801f2a-41fd-4b5c-ac90-074211744af6"
                    },
                    "status": "final",
                    "category": "principal",
                    "extension": [
                      {
                        "url": "hypothesis",
                        "valueBoolean": "true"
                      }
                    ],
                    "code": {
                      "text": "J45.0",
                      "coding": [
                        {
                          "system": "2.16.840.1.113883.6.3",
                          "type": "CID-10",
                          "code": "J45.0",
                          "display": "Asma predominantemente alérgic"
                        }
                      ],
                      "status": "S"
                    },
                    "subject": {
                      "display": "MARIA JONES NUNES",
                      "reference": "Patient/a32e05f3-cf45-42c8-bbbc-8566ebedc119"
                    },
                    "issued": "2019-07-31T21:45:11-0300"
                  }
                },
                {
                  "resource": {
                    "resourceType": "AllergyIntolerance",
                    "id": "d902e74f-d483-46cd-b4f4-d19cc77632f1",
                    "identifier": [
                      {
                        "system": "http://acme.com/ids/patients/risks",
                        "value": "494762223"
                      }
                    ],
                    "type": "allergy",
                    "category": [
                      "food"
                    ],
                    "patient": {
                      "display": "MARIA JONES NUNES",
                      "reference": "Patient/a32e05f3-cf45-42c8-bbbc-8566ebedc119"
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "reaction": [
                      {
                        "substance": {
                          "text": "Amendoin"
                        },
                        "manifestation": [
                          {
                            "text": "Reação anafilática"
                          }
                        ],
                        "description": "Intolerância a Amendoin"
                      }
                    ]
                  }
                },
                {
                  "resource": {
                    "resourceType": "DocumentReference",
                    "id": "2f39493b-5a5f-4108-b842-e5b157e2766d",
                    "status": "final",
                    "author": [
                      {
                        "reference": "Practictioner/52091-SP"
                      }
                    ],
                    "content": [
                      {
                        "attachment": {
                          "title": "PRESCRICAO DE MEDICACAO"
                        }
                      }
                    ],
                    "context": {
                      "encounter": {
                        "id": "Encounter/76876876876"
                      }
                    },
                    "subject": {
                      "display": "MARCELO DA SILVA",
                      "reference": "Patient/423643a6-6d3d-4cb0-a9c7-3e5a7304c572"
                    },
                    "type": {
                      "coding": [
                        {
                          "id": "57833-6",
                          "system": "LOINC"
                        }
                      ],
                      "text": "ANAMNESE"
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "b46e24d7-208a-4154-8c8f-cc8e7c526c52",
                    "code": {
                      "coding": [
                        {
                          "code": "AMBULATORIO",
                          "display": "AMBULATORIO",
                          "system": "HL7"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/2f39493b-5a5f-4108-b842-e5b157e2766d"
                    },
                    "subject": {
                      "display": "MARCELO DA SILVA",
                      "reference": "Patient/423643a6-6d3d-4cb0-a9c7-3e5a7304c572"
                    },
                    "value": [
                      {
                        "system": "urn:oid:2.16.840.1.113883.2.21.1.122",
                        "code": "90159110",
                        "display": "AMARYL 3 MG"
                      }
                    ],
                    "valueString": "AMARYL 3 MG-Tomar 1 cp à tarde"
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "b46e24d7-208a-4154-8c8f-cc8e7c526c52",
                    "code": {
                      "coding": [
                        {
                          "system": "HL7",
                          "code": "3141-9",
                          "display": "Peso"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/2f39493b-5a5f-4108-b842-e5b157e2766d"
                    },
                    "subject": {
                      "display": "MARCELO DA SILVA",
                      "reference": "Patient/423643a6-6d3d-4cb0-a9c7-3e5a7304c572"
                    },
                    "valueQuantity": {
                      "value": 83
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "b46e24d7-208a-4154-8c8f-cc8e7c526c52",
                    "code": {
                      "coding": [
                        {
                          "system": "HL7",
                          "code": "8302-2",
                          "display": "Altura"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/2f39493b-5a5f-4108-b842-e5b157e2766d"
                    },
                    "subject": {
                      "display": "MARCELO DA SILVA",
                      "reference": "Patient/423643a6-6d3d-4cb0-a9c7-3e5a7304c572"
                    },
                    "valueQuantity": {
                      "value": 1.75
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "DiagnosticReport",
                    "id": "b029e259-0876-4837-bc64-a3132873fcab",
                    "identifier": [
                      {
                        "system": "2.16.840.1.113883.6.3",
                        "type": "CID-10"
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/61762b45-1ce8-47c0-abe4-67a819bccfd9"
                    },
                    "status": "final",
                    "category": "previous",
                    "extension": [
                      {
                        "url": "familyRelationship",
                        "valueString": "pai"
                      }
                    ],
                    "code": {
                      "text": "I10",
                      "coding": [
                        {
                          "system": "2.16.840.1.113883.6.3",
                          "type": "CID-10",
                          "code": "I10",
                          "display": "Hipertensão essencial"
                        }
                      ],
                      "status": "S"
                    },
                    "subject": {
                      "display": "MARCELO DA SILVA",
                      "reference": "Patient/423643a6-6d3d-4cb0-a9c7-3e5a7304c572"
                    },
                    "issued": "2019-07-31T21:45:11-0300"
                  }
                },
                {
                  "resource": {
                    "resourceType": "DocumentReference",
                    "id": "3db61c87-104e-48d0-a783-8a5cbc66c21b",
                    "status": "final",
                    "author": [
                      {
                        "reference": "Practictioner/51242-SP"
                      }
                    ],
                    "content": [
                      {
                        "attachment": {
                          "title": "PRESCRICAO DE MEDICACAO"
                        }
                      }
                    ],
                    "context": {
                      "encounter": {
                        "id": "Encounter/76876876876"
                      }
                    },
                    "subject": {
                      "display": "NILZA PINHEIRO",
                      "reference": "Patient/72bafc04-1efa-490c-af95-5c7a31b4b20c"
                    },
                    "type": {
                      "coding": [
                        {
                          "id": "57833-6",
                          "system": "LOINC"
                        }
                      ],
                      "text": "ANAMNESE"
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "ba1b78cf-c2d1-478f-b443-78db8859e75f",
                    "code": {
                      "coding": [
                        {
                          "code": "AMBULATORIO",
                          "display": "AMBULATORIO",
                          "system": "HL7"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/3db61c87-104e-48d0-a783-8a5cbc66c21b"
                    },
                    "subject": {
                      "display": "NILZA PINHEIRO",
                      "reference": "Patient/72bafc04-1efa-490c-af95-5c7a31b4b20c"
                    },
                    "extension": [
                      {
                        "url": "continuous",
                        "valueBoolean": "true"
                      }
                    ],
                    "value": [
                      {
                        "system": "urn:oid:2.16.840.1.113883.2.21.1.122",
                        "code": "90159110",
                        "display": "AMARYL 3 MG"
                      }
                    ],
                    "valueString": "AMARYL 3 MG-Tomar 1 cp à tarde"
                  }
                },
                {
                  "resource": {
                    "resourceType": "DiagnosticReport",
                    "id": "0661982f-9116-4aa5-b6c0-79fe5ff5a27a",
                    "identifier": [
                      {
                        "system": "2.16.840.1.113883.6.3",
                        "type": "CID-10"
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/5e826a53-cad9-40c3-b71c-909e6f08b440"
                    },
                    "status": "final",
                    "category": "principal",
                    "extension": [
                      {
                        "url": "hypothesis",
                        "valueBoolean": "true"
                      }
                    ],
                    "code": {
                      "text": "J45.0",
                      "coding": [
                        {
                          "system": "2.16.840.1.113883.6.3",
                          "type": "CID-10",
                          "code": "J45.0",
                          "display": "Lúpus eritematoso disseminado (sistêmico) não especificado"
                        }
                      ],
                      "status": "S"
                    },
                    "subject": {
                      "display": "NILZA PINHEIRO",
                      "reference": "Patient/72bafc04-1efa-490c-af95-5c7a31b4b20c"
                    },
                    "issued": "2019-07-31T21:45:11-0300"
                  }
                },
                {
                  "resource": {
                    "resourceType": "DiagnosticReport",
                    "id": "0661982f-9116-4aa5-b6c0-79fe5ff5a27a",
                    "identifier": [
                      {
                        "system": "2.16.840.1.113883.6.3",
                        "type": "CID-10"
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/5e826a53-cad9-40c3-b71c-909e6f08b440"
                    },
                    "status": "final",
                    "category": "previous",
                    "code": {
                      "text": "J45.0",
                      "coding": [
                        {
                          "system": "2.16.840.1.113883.6.3",
                          "type": "CID-10",
                          "code": "J45.0",
                          "display": "Lúpus eritematoso disseminado (sistêmico) não especificado"
                        }
                      ],
                      "status": "S"
                    },
                    "subject": {
                      "display": "NILZA PINHEIRO",
                      "reference": "Patient/72bafc04-1efa-490c-af95-5c7a31b4b20c"
                    },
                    "issued": "2019-07-31T21:45:11-0300"
                  }
                },
                {
                  "resource": {
                    "resourceType": "DiagnosticReport",
                    "id": "0661982f-9116-4aa5-b6c0-79fe5ff5a27a",
                    "identifier": [
                      {
                        "system": "2.16.840.1.113883.6.3",
                        "type": "CID-10"
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/5e826a53-cad9-40c3-b71c-909e6f08b440"
                    },
                    "status": "final",
                    "category": "previous",
                    "extension": [
                      {
                        "url": "familyRelationship",
                        "valueString": "mãe"
                      }
                    ],
                    "code": {
                      "text": "J45.0",
                      "coding": [
                        {
                          "system": "2.16.840.1.113883.6.3",
                          "type": "CID-10",
                          "code": "J45.0",
                          "display": "Lúpus eritematoso disseminado (sistêmico) não especificado"
                        }
                      ],
                      "status": "S"
                    },
                    "subject": {
                      "display": "NILZA PINHEIRO",
                      "reference": "Patient/72bafc04-1efa-490c-af95-5c7a31b4b20c"
                    },
                    "issued": "2019-07-31T21:45:11-0300"
                  }
                },
                {
                  "resource": {
                    "resourceType": "AllergyIntolerance",
                    "id": "22e355ac-e762-4c93-bbe3-72c0a63f40ed",
                    "identifier": [
                      {
                        "system": "http://acme.com/ids/patients/risks",
                        "value": "494762223"
                      }
                    ],
                    "type": "allergy",
                    "category": [
                      "medication"
                    ],
                    "patient": {
                      "display": "NILZA PINHEIRO",
                      "reference": "Patient/72bafc04-1efa-490c-af95-5c7a31b4b20c"
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "reaction": [
                      {
                        "substance": {
                          "text": "Aspirina"
                        },
                        "manifestation": [
                          {
                            "text": "Falta de ar"
                          }
                        ],
                        "description": "Alergia a aspirina"
                      }
                    ]
                  }
                },
                {
                  "resource": {
                    "resourceType": "AllergyIntolerance",
                    "id": "22e355ac-e762-4c93-bbe3-72c0a63f40ed",
                    "identifier": [
                      {
                        "system": "http://acme.com/ids/patients/risks",
                        "value": "494762223"
                      }
                    ],
                    "type": "intolerance",
                    "category": [
                      "food"
                    ],
                    "patient": {
                      "display": "NILZA PINHEIRO",
                      "reference": "Patient/72bafc04-1efa-490c-af95-5c7a31b4b20c"
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "reaction": [
                      {
                        "substance": {
                          "text": "Extrato de caju"
                        },
                        "manifestation": [
                          {
                            "text": "Falta de ar"
                          }
                        ],
                        "description": "Intolerância a Extrato de caju"
                      },
                      {
                        "substance": {
                          "text": "Extrato de acerola"
                        },
                        "manifestation": [
                          {
                            "text": "Falta de ar"
                          }
                        ],
                        "description": "Intolerância a Extrato de acerola"
                      },
                      {
                        "substance": {
                          "text": "Extrato de jabuticaba"
                        },
                        "manifestation": [
                          {
                            "text": "Falta de ar"
                          }
                        ],
                        "description": "Intolerância a Extrato de jabuticaba"
                      }
                    ]
                  }
                },
                {
                  "resource": {
                    "resourceType": "QuestionnaireResponse",
                    "id": "20171121-1657770794",
                    "item": [
                      {
                        "linkId": "fitnessActivities",
                        "text": "Pratica atividade física",
                        "answer": [
                          {
                            "valueString": "Sim"
                          }
                        ]
                      },
                      {
                        "linkId": "smoke",
                        "text": "Fuma",
                        "answer": [
                          {
                            "valueString": "Não"
                          }
                        ]
                      },
                      {
                        "linkId": "alcohol",
                        "text": "Bebidas alcolicas",
                        "answer": [
                          {
                            "valueString": "Sim, eventualmente"
                          }
                        ]
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "status": "final",
                    "subject": {
                      "display": "NILZA PINHEIRO",
                      "reference": "Patient/72bafc04-1efa-490c-af95-5c7a31b4b20c"
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "DocumentReference",
                    "id": "055849a3-db82-42c1-a9fe-38647d91e0fd",
                    "status": "final",
                    "author": [
                      {
                        "reference": "Practictioner/52091-SP"
                      }
                    ],
                    "content": [
                      {
                        "attachment": {
                          "title": "PRESCRICAO DE MEDICACAO"
                        }
                      }
                    ],
                    "context": {
                      "encounter": {
                        "id": "Encounter/76876876876"
                      }
                    },
                    "subject": {
                      "display": "CARLA DA SILVA",
                      "reference": "Patient/d7a0e050-2c21-46bc-aa36-0ecaa7ee9e54"
                    },
                    "type": {
                      "coding": [
                        {
                          "id": "57833-6",
                          "system": "LOINC"
                        }
                      ],
                      "text": "ANAMNESE"
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "aa08914c-dfe4-415b-b69d-bee716ebf627",
                    "code": {
                      "coding": [
                        {
                          "system": "HL7",
                          "code": "3141-9",
                          "display": "Peso"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/055849a3-db82-42c1-a9fe-38647d91e0fd"
                    },
                    "subject": {
                      "display": "CARLA DA SILVA",
                      "reference": "Patient/d7a0e050-2c21-46bc-aa36-0ecaa7ee9e54"
                    },
                    "valueQuantity": {
                      "value": 80
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "aa08914c-dfe4-415b-b69d-bee716ebf627",
                    "code": {
                      "coding": [
                        {
                          "system": "HL7",
                          "code": "8302-2",
                          "display": "Altura"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/055849a3-db82-42c1-a9fe-38647d91e0fd"
                    },
                    "subject": {
                      "display": "CARLA DA SILVA",
                      "reference": "Patient/d7a0e050-2c21-46bc-aa36-0ecaa7ee9e54"
                    },
                    "valueQuantity": {
                      "value": 1.6
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "DiagnosticReport",
                    "id": "4a5b5b17-65f1-449b-8a24-ef8e830c4950",
                    "identifier": [
                      {
                        "system": "2.16.840.1.113883.6.3",
                        "type": "CID-10"
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "Encounter/76876876876"
                    },
                    "status": "final",
                    "category": "principal",
                    "extension": [
                      {
                        "url": "hypothesis",
                        "valueBoolean": "true"
                      }
                    ],
                    "code": {
                      "text": "R06.2",
                      "coding": [
                        {
                          "system": "2.16.840.1.113883.6.3",
                          "type": "CID-10",
                          "code": "R06.2",
                          "display": "Respiração ofegante"
                        }
                      ],
                      "status": "S"
                    },
                    "subject": {
                      "display": "CARLA DA SILVA",
                      "reference": "Patient/d7a0e050-2c21-46bc-aa36-0ecaa7ee9e54"
                    },
                    "issued": "2019-07-31T21:45:11-0300"
                  }
                },
                {
                  "resource": {
                    "resourceType": "QuestionnaireResponse",
                    "id": "20171121-1657770794",
                    "item": [
                      {
                        "linkId": "fitnessActivities",
                        "text": "Pratica atividade física",
                        "answer": [
                          {
                            "valueString": "Não"
                          }
                        ]
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "status": "final",
                    "subject": {
                      "display": "CARLA DA SILVA",
                      "reference": "Patient/d7a0e050-2c21-46bc-aa36-0ecaa7ee9e54"
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "DocumentReference",
                    "id": "01297599-6d01-4571-8c21-f9eb6ea47868",
                    "status": "final",
                    "author": [
                      {
                        "reference": "Practictioner/51242-SP"
                      }
                    ],
                    "content": [
                      {
                        "attachment": {
                          "title": "PRESCRICAO DE MEDICACAO"
                        }
                      }
                    ],
                    "context": {
                      "encounter": {
                        "id": "Encounter/76876876876"
                      }
                    },
                    "subject": {
                      "display": "RICARDO FERNANDER ARAGÃO",
                      "reference": "Patient/2d2ec3bf-0648-4630-b6d6-ed2c00b86887"
                    },
                    "type": {
                      "coding": [
                        {
                          "id": "57833-6",
                          "system": "LOINC"
                        }
                      ],
                      "text": "ANAMNESE"
                    }
                  }
                },
                {
                  "resource": {
                    "resourceType": "Observation",
                    "id": "c1e1397f-5764-4449-95d1-2b5a9d9d3ea4",
                    "code": {
                      "coding": [
                        {
                          "code": "AMBULATORIO",
                          "display": "AMBULATORIO",
                          "system": "HL7"
                        }
                      ]
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/01297599-6d01-4571-8c21-f9eb6ea47868"
                    },
                    "subject": {
                      "display": "RICARDO FERNANDER ARAGÃO",
                      "reference": "Patient/2d2ec3bf-0648-4630-b6d6-ed2c00b86887"
                    },
                    "extension": [
                      {
                        "url": "continuous",
                        "valueBoolean": "true"
                      }
                    ],
                    "value": [
                      {
                        "system": "urn:oid:2.16.840.1.113883.2.21.1.122",
                        "code": "90021444",
                        "display": "ASPIRINA PREVENT 100 MG"
                      }
                    ],
                    "valueString": "ASPIRINA PREVENT 100 MG Tomar 1 vez ao dia"
                  }
                },
                {
                  "resource": {
                    "resourceType": "DiagnosticReport",
                    "id": "99bf94a8-3ca4-43ec-886b-48f8da0220d8",
                    "identifier": [
                      {
                        "system": "2.16.840.1.113883.6.3",
                        "type": "CID-10"
                      }
                    ],
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "partOf": {
                      "reference": "DocumentReference/4f7a37dc-14c2-42c8-9b85-bfacb550a872"
                    },
                    "status": "final",
                    "category": "principal",
                    "extension": [
                      {
                        "url": "hypothesis",
                        "valueBoolean": "true"
                      }
                    ],
                    "code": {
                      "text": "H10",
                      "coding": [
                        {
                          "system": "2.16.840.1.113883.6.3",
                          "type": "CID-10",
                          "code": "H10",
                          "display": "Conjuntivite"
                        }
                      ],
                      "status": "S"
                    },
                    "subject": {
                      "display": "RICARDO FERNANDER ARAGÃO",
                      "reference": "Patient/2d2ec3bf-0648-4630-b6d6-ed2c00b86887"
                    },
                    "issued": "2019-07-31T21:45:11-0300"
                  }
                },
                {
                  "resource": {
                    "resourceType": "AllergyIntolerance",
                    "id": "f3ced1eb-94f8-4a78-ab0d-6bd79b368375",
                    "identifier": [
                      {
                        "system": "http://acme.com/ids/patients/risks",
                        "value": "494762223"
                      }
                    ],
                    "type": "allergy",
                    "category": [
                      "medication"
                    ],
                    "patient": {
                      "display": "RICARDO FERNANDER ARAGÃO",
                      "reference": "Patient/2d2ec3bf-0648-4630-b6d6-ed2c00b86887"
                    },
                    "encounter": {
                      "reference": "Encounter/76876876876"
                    },
                    "reaction": [
                      {
                        "substance": {
                          "text": "Atracúrio"
                        },
                        "manifestation": [
                          {
                            "text": "Falta de ar"
                          }
                        ],
                        "description": "Alergia a Atracúrio"
                      }
                    ]
                  }
                }
              ]
            }
+ Response 400 (application/json)
    + Body

            {
              "resourceType": "Bundle",
              "id": "bundle-search-warning",
              "meta": {
                "lastUpdated": "2017-03-14T08:23:30+11:00"
              },
              "type": "searchset",
              "total": 0,
              "link": [
                {
                  "relation": "self",
                  "url": "https://example.dataopera.com.br/fhir/_history?Patient.identifier=22dfc93b-7864-3453-83f2-b6907e4d6389"
                }
              ],
              "entry": [
                {
                  "resource": {
                    "resourceType": "OperationOutcome",
                    "id": "warning",
                    "issue": [
                      {
                        "severity": "warning",
                        "code": "bad-request",
                        "details": {
                          "text": "O recurso não pôde ser analisado ou falhou nas regras básicas de validação do FHIR"
                        }
                      }
                    ]
                  },
                  "search": {
                    "mode": "outcome"
                  }
                }
              ]
            }

            
+ Response 401 (application/json)
    + Body

            {
              "resourceType": "Bundle",
              "id": "bundle-search-warning",
              "meta": {
                "lastUpdated": "2017-03-14T08:23:30+11:00"
              },
              "type": "searchset",
              "total": 0,
              "link": [
                {
                  "relation": "self",
                  "url": "https://example.dataopera.com.br/fhir/_history?Patient.identifier=22dfc93b-7864-3453-83f2-b6907e4d6389"
                }
              ],
              "entry": [
                {
                  "resource": {
                    "resourceType": "OperationOutcome",
                    "id": "warning",
                    "issue": [
                      {
                        "severity": "warning",
                        "code": "not-authorized",
                        "details": {
                          "text": "Acesso não autorizado"
                        }
                      }
                    ]
                  },
                  "search": {
                    "mode": "outcome"
                  }
                }
              ]
            }

+ Response 404 (application/json)
    + Body

            {
              "resourceType": "Bundle",
              "id": "bundle-search-warning",
              "meta": {
                "lastUpdated": "2017-03-14T08:23:30+11:00"
              },
              "type": "searchset",
              "total": 0,
              "link": [
                {
                  "relation": "self",
                  "url": "https://example.dataopera.com.br/fhir/_history?Patient.identifier=22dfc93b-7864-3453-83f2-b6907e4d6389"
                }
              ],
              "entry": [
                {
                  "resource": {
                    "resourceType": "OperationOutcome",
                    "id": "warning",
                    "issue": [
                      {
                        "severity": "warning",
                        "code": "not-found",
                        "details": {
                          "text": "Tipo de recurso não suportado ou não é um endpoint FHIR"
                        }
                      }
                    ]
                  },
                  "search": {
                    "mode": "outcome"
                  }
                }
              ]
            }
            
        


# Group DataMea - Visualizador de dados clinicos

## Visualização de Dados Clínicos no DataMea (modo App Embedeed) com autenticação Oauth

Este modo serve para abrir o DataMea (solução de visualização de dados clínicos) integrado a alguma aplicação sem apresentar o login para o usuário. 
Primeiramente deve ser realizada autenticação oauth, especificada acima neste documento, informando paciente e profissional logado, após deve ser chamada a aplicação do DataMea informando o token gerado por parâmetro.

### Exemplo de chamada do DataMea

> https://datamea.com.br/index.html?token=dfb12337d6a24f7b26123e9bc991234590844b1d 


### Exemplo de implementação 

Para auxiliar na implementação, segue um exemplo em Javascript. 
Vale lembrar que é somente uma ilustração, cada sistema/linguagem tem suas características e necessidades.

>$.ajax({ 
>   type: 'POST', 
>   url: "https://tune.dataopera.com.br/api/oauth", 
>   data: { 
>       "grant_type": "client_credentials", 
>       "client_id": "CLIENT-ID-FORNECIDO", 
>       "client_secret": "PASSWORD_FORNECIDO", 
>       "patient": { 
>           "publicToken": "08650301432965004", 
>           "nome": "Marlene de Souza Antunes", 
>           "doc-cpf": "11111111111"
>        },
>       "professional": { 
>           "publicToken": "08650301432965004", 
>           "nome": "Marlene de Souza Antunes", 
>           "doc-cpf": "11111111111"
>        }
>   }, 
>   dataType: "json", 
>   contentType: 'application/x-www-form-urlencoded; 
>   charset=utf-8', 
>   xhrFields: { withCredentials: true }, 
>   success: function (result) { 
>       var token = result; 
>       $(location).attr('href', https://datamea.com.br/index.html?token='+ token; 
>   }, 
>    error: function (req, status, error) { 
>        alert(error); 
>    } 
>});