FORMAT: 1A
HOST:  https://datamea.com.br/


# Group Consumo do DataMea

## Visualização de Dados Clínicos no DataMea (modo App Embedeed) com autenticação Oauth [/index.html?token={token}]      

Este modo serve para abrir o DataMea (solução de visualização de dados clínicos) integrado a alguma aplicação sem apresentar o login para o usuário. 
Primeiramente deve ser realizada autenticação oauth, especificada acima neste documento, informando paciente e profissional logado, após deve ser chamada a aplicação do DataMea informando o token gerado por parâmetro.

### Exemplo de chamada do DataMea

> https://datamea.com.br/index.html?token=dfba7e37d6a24f7b263bde9bc99cd23590844b1d 


### Exemplo de imlplementação 

Para auxiliar na implementação, segue um exemplo em Javascript. 
Vale lembrar que é somente uma ilustração, cada sistema/linguagem tem suas características e necessidades.

>$.ajax({ 
>   type: 'POST', 
>   url: "https://tune.dataopera.com.br/api/oauth", 
>   data: { 
>       "grant_type": "client_credentials", 
>       "client_id": "CLIENT-ID-FORNECIDO", 
>       "client_secret": "PASSWORD_FORNECIDO", 
>       "patient": { 
>           "publicToken": "08650301432965004", 
>           "nome": "Marlene de Souza Antunes", 
>           "doc-cpf": "11111111111"
>        } }, 
>   dataType: "json", 
>   contentType: 'application/x-www-form-urlencoded; 
>   charset=utf-8', 
>   xhrFields: { withCredentials: true }, 
>   success: function (result) { 
>       var token = result; 
>       $(location).attr('href', https://datamea.com.br/index.html?token='+ token; 
>   }, 
>    error: function (req, status, error) { 
>        alert(error); 
>    } 
>});
