# Group Especificação de perfil de recursos de dados clinicos

Para fins de entendimento, segue definição de alguns recursos FHIR utilizados em nosso perfil de interoperabilidade.
A definição de todos os conjuntos de dados deve ser elaborada durante a definição do CMD (conjunto minimo de dados) no processo do projeto.
Lembrando que a documentação oficial do HL7 FHIR pode ser acessada no site oficial do  **[HL7 FHIR](https://hl7.org/fhir/)**.

