FORMAT: 1A
HOST: https://man-api.herokuapp.com/

# DTO - DataOpera

O **DataOpera®** é um produto desenvolvido pela DTO, que reúne e padroniza informações de pacientes de diversos sistemas de saúde (hospitais, clínicas, laboratórios, consultórios médicos, seguradoras, etc.), armazena de forma segura e disponibiliza apenas quando autorizado pelo beneficiário, conforme LGPD.

O **DataOpera®** é uma plataforma Web com arquitetura robusta e escalável que contém um Barramento de Interoperabilidade, um Repositório de dados estruturados e um Visualizador clínico para os pacientes e seus médicos.

Tudo pensado para facilitar o acesso e distribuição de dados de saúde entre pacientes e prestadores de serviço, resultando em um atendimento objetivo, eficiente e humanizado. Colocando a tecnologia a serviço da saúde.

**Por que o DataOpera®**?

O **DataOpera®**, além de beneficiar todos os players envolvidos nesse cenário da saúde, encontra forte embasamento e incentivo legal.

**Alguns dos Benefícios em escolher o DataOpera**:

- Possibilita a integração de dados da Saúde Pública e Saúde Suplementar

- Empodera o Paciente, permitindo que ele compartilhe suas informações de saúde com quem ele quiser.

- Reduz custos de saúde, facilita a gestão populacional e melhora a qualidade assistencial.

- Auxilia a TI das empresas de saúde, pois minimiza a dependência de software e serviços de terceiros, permite a unificação dos dados com menor uso de integrações ponto a ponto (ou sistema a sistema) e dá maior flexibilidade para implementações futuras de novas funcionalidades.

- **Inovação e Pioneirismo com HL7®️ FHIR®️**

A **DTO** se orgulha de ser pioneira na implementação do padrão **HL7®️ FHIR®️** no Brasil, um marco na troca de dados de saúde de forma ágil e segura. Este feito sublinha nosso compromisso com a vanguarda tecnológica e interoperabilidade, elevando o patamar de soluções em saúde no país. 

Com o HL7®️ FHIR®️ na plataforma DataOpera®, consolidamos informações médicas dispersas, proporcionando uma visão completa e integrada do histórico de saúde dos pacientes. Esta inovação impacta diretamente na qualidade e eficácia do atendimento. 

Nossa liderança no uso do **HL7®️ FHIR®️** se traduz em soluções eficientes, tais como a centralização de dados e a potencialização da medicina preventiva. Assim, reafirmamos nosso compromisso com a saúde e o bem-estar dos pacientes, colocando a DTO à frente da transformação digital na saúde brasileira. 

![Texto Alternativo](https://github.com/dataopera/dataopera_spec/blob/master/images/datamea/HL7FHIR.png?raw=true)